export const productsMock = [
    {
        name: "Porsche 356A Speedster",
        model: "356A",
        price: 125000,
        description: "Un icónico roadster de los años 50 con diseño elegante y liviano.",
        image: "https://cdn.dealeraccelerate.com/ecpch/2/576/23613/790x1024/w/1956-porsche-356a-speedster",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        name: "Porsche 911 Carrera RS 2.7",
        model: "911 RS 2.7",
        price: 280000,
        description: "El legendario RS de 1973 con su clásico alerón 'cola de pato'.",
        image: "https://robbreport.com/wp-content/uploads/2023/12/1-w-1973-Porsche-Carrera-RS-2.7-Homologation_4.jpg?w=1000",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        name: "Porsche 914",
        model: "914",
        price: 48000,
        description: "Coupé deportivo con motor central producido en colaboración con Volkswagen.",
        image: "https://www.autocentrum.pl/ZS05MTQudTJRVztnfg54JhIPb3swFnc1WVkoezAHLjpTWSh7ZE1jYARRfTVkTWgwB1EsZTNHOzJSBClsfgU1IUNWJTF8TGtnHl89M3MI",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        name: "Porsche 550 Spyder",
        model: "550",
        price: 320000,
        description: "Modelo de competición ligero y ágil, famoso por su historia y diseño.",
        image: "https://www.amalgamcollection.com/cdn/shop/products/DSCF4988WIDE_2000x850_crop_center.jpg?v=1706094293",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        name: "Porsche 928",
        model: "928",
        price: 65000,
        description: "Gran turismo con motor V8, lanzado como el futuro reemplazo del 911.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Porsche_928_Parkers_Piece.JPG/1024px-Porsche_928_Parkers_Piece.JPG",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        name: "Porsche 930 Turbo",
        model: "930",
        price: 150000,
        description: "El primer 911 con turbo, conocido por su potencia y conducción desafiante.",
        image: "https://www.topgear.com/sites/default/files/2024/07/1%20Porsche%20930%20Turbo%20review.jpg?w=892&h=502",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        name: "Porsche 944",
        model: "944",
        price: 35000,
        description: "Modelo de motor delantero popular por su equilibrio y manejo.",
        image: "https://hips.hearstapps.com/hmg-prod/images/1989-porsche-944-104-1-673e1ff35e2ca.jpg?crop=0.774xw:0.773xh;0.104xw,0.140xh&resize=1200:*",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        name: "Porsche 912",
        model: "912",
        price: 60000,
        description: "Versión más accesible del 911 con motor de 4 cilindros.",
        image: "https://www.gallery-aaldering.com/wp-content/uploads/2021/07/porsche-912-1966.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        name: "Porsche 959",
        model: "959",
        price: 1200000,
        description: "Superdeportivo de los 80 con tecnología revolucionaria para su época.",
        image: "https://uncrate.com/assets_c/2024/01/porsche-959-1-thumb-960xauto-169967.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        name: "Porsche 911 Targa",
        model: "911 Targa",
        price: 100000,
        description: "Versión semi-descapotable del 911 con techo removible y barra antivuelco.",
        image: "https://hips.hearstapps.com/hmg-prod/images/theongbr003targa-19-66142d9e63dce.jpg?crop=1.00xw:1.00xh;0,0&resize=1200:*",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        name: "Porsche 911 SC",
        model: "911 SC",
        price: 95000,
        description: "Producción entre 1978-1983, muy valorado por su fiabilidad mecánica.",
        image: "https://cdn.soulauto.com/wp-content/uploads/2024/06/00_00_Porsche911SCTurbo_01-0108-800x436.jpg?x32428",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        name: "Porsche 911 Carrera 3.2",
        model: "Carrera 3.2",
        price: 110000,
        description: "El sucesor del 911 SC, considerado el último 911 clásico.",
        image: "https://prestigeandperformancecar.com/wp-content/uploads/HDK-1937-900x563.jpg.webp",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        name: "Porsche 924",
        model: "924",
        price: 29000,
        description: "Modelo de entrada con motor delantero y diseño accesible.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Porsche_924_in_the_Porsche-Museum_%282009%29_1X7A0347.jpg/1024px-Porsche_924_in_the_Porsche-Museum_%282009%29_1X7A0347.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        name: "Porsche 964 Carrera",
        model: "964",
        price: 135000,
        description: "Versión moderna del 911 con tracción total y suspensión mejorada.",
        image: "https://www.gts-models.com/wp-content/uploads/2018/07/porsche-911-964-carrera-4-01.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        name: "Porsche 911 Turbo S (964)",
        model: "964 Turbo S",
        price: 250000,
        description: "Edición limitada de alto rendimiento del 911 Turbo clásico.",
        image: "https://images.squarespace-cdn.com/content/v1/5caed8960cf57d49530e8c60/1632156930286-5DRDAUKRUJ6J2HKXGAJR/art-mg-porsche964turbo33s2.jpg?format=1500w",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        name: "Porsche 993 Carrera",
        model: "993",
        price: 160000,
        description: "Último 911 refrigerado por aire, muy buscado por coleccionistas.",
        image: "https://www.pcarmarket.com/static/media/uploads/galleries/photos/uploads/galleries/14909-chin-1997-porsche-carrera-2s-black/.thumbnails/jpg.-02.jpg/jpg.-02-tiny-2048x0-0.5x0.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        name: "Porsche 911 S (1967)",
        model: "911 S",
        price: 190000,
        description: "Uno de los primeros 911 con mayor potencia y mejor manejo.",
        image: "https://uncrate.com/assets_c/2017/09/67-911s-1-thumb-960xauto-75859.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        name: "Porsche 356B Coupe",
        model: "356B",
        price: 110000,
        description: "Versión más moderna del 356, refinada y estilizada.",
        image: "https://cdn.dealeraccelerate.com/ecpch/2/739/34470/790x1024/w/1963-porsche-356b-coupe",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        name: "Porsche 911E",
        model: "911E",
        price: 130000,
        description: "Modelo de lujo con inyección mecánica, ideal para conducción diaria.",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/6e/1967_Porsche_911S.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        name: "Porsche 964 RS America",
        model: "964 RS",
        price: 210000,
        description: "Edición especial y ligera enfocada en el rendimiento puro.",
        image: "https://www.pcarmarket.com/static/media/uploads/galleries/photos/uploads/galleries/-rs-america-red/.thumbnails/IMG_4357.jpg/IMG_4357-tiny-2048x0-0.5x0.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
];
